### ISSUE TITLE
Incorrect journal URL in the class file

### ISSUE THREAD

**Issue by wenjie2wang** [vtex-soft/texsupport.ruc-jds#1]
It seems that the URL of the journal in the class file is incorrect: 

https://github.com/vtex-soft/texsupport.ruc-jds/blob/a19e6df286d6ff0362e16bfa37b110d4b89fbac7/jdsart.cls#L104

which should be https://jds-online.org.

Also, IMHO, all the URLs should start with `https://` instead of `http://` if applicable.
https://github.com/vtex-soft/texsupport.ruc-jds/blob/a19e6df286d6ff0362e16bfa37b110d4b89fbac7/jdsart.cls#L132
https://github.com/vtex-soft/texsupport.ruc-jds/blob/a19e6df286d6ff0362e16bfa37b110d4b89fbac7/jdsart.cls#L141
https://github.com/vtex-soft/texsupport.ruc-jds/blob/a19e6df286d6ff0362e16bfa37b110d4b89fbac7/jdsart.cls#L350

cc @jun-yan

**Comment by lstonys** [comment]
Thanks for a note. Fixed.

**Comment by wenjie2wang** [comment]
Thanks for your quick action.  However, the URL to the journal home page is still wrong.

https://github.com/vtex-soft/texsupport.ruc-jds/blob/a2d5b14a0a2463fb772029cc6c604110f1416b9e/jdsart.cls#L104

The correct URL is again https://jds-online.org.

**Comment by lstonys** [comment]
ups. Fixed
